# Everything about Numpy                                                                     

In [1]:
import numpy as np

In [2]:
arr= np.array([[1,3,5], [2,6,8], [3,4,9]])

In [3]:
arr

array([[1, 3, 5],
       [2, 6, 8],
       [3, 4, 9]])

In [4]:
arr2= np.array([[34,23,17], [78,62,10], [99,73,55]])

In [5]:
arr2


array([[34, 23, 17],
       [78, 62, 10],
       [99, 73, 55]])

In [6]:
np.shape(arr)

(3, 3)

In [7]:
np.shape(arr2)

(3, 3)

In [8]:
arr.T

array([[1, 2, 3],
       [3, 6, 4],
       [5, 8, 9]])

In [9]:
arr

array([[1, 3, 5],
       [2, 6, 8],
       [3, 4, 9]])

In [10]:
arr.real

array([[1, 3, 5],
       [2, 6, 8],
       [3, 4, 9]])

In [11]:
arr.ravel()

array([1, 3, 5, 2, 6, 8, 3, 4, 9])

In [12]:
arr.sum(axis=1)

array([ 9, 16, 16])

In [13]:
arr.sum(axis=0)

array([ 6, 13, 22])

In [14]:
arr.argmax()

8

In [15]:
arr

array([[1, 3, 5],
       [2, 6, 8],
       [3, 4, 9]])

In [16]:
arr.argmin()

0

In [17]:
a= np.random.rand(3,4)

In [18]:
a

array([[0.11852662, 0.36664711, 0.2734895 , 0.44790939],
       [0.03946031, 0.13107506, 0.9630862 , 0.46454213],
       [0.32794182, 0.53552584, 0.42094706, 0.95377637]])

In [19]:
a.ravel()

array([0.11852662, 0.36664711, 0.2734895 , 0.44790939, 0.03946031,
       0.13107506, 0.9630862 , 0.46454213, 0.32794182, 0.53552584,
       0.42094706, 0.95377637])

In [20]:
a.reshape(6,2)

array([[0.11852662, 0.36664711],
       [0.2734895 , 0.44790939],
       [0.03946031, 0.13107506],
       [0.9630862 , 0.46454213],
       [0.32794182, 0.53552584],
       [0.42094706, 0.95377637]])

In [21]:
a.argsort()

array([[0, 2, 1, 3],
       [0, 1, 3, 2],
       [0, 2, 1, 3]], dtype=int64)

In [22]:
a=a.reshape(4,3)

In [23]:
a

array([[0.11852662, 0.36664711, 0.2734895 ],
       [0.44790939, 0.03946031, 0.13107506],
       [0.9630862 , 0.46454213, 0.32794182],
       [0.53552584, 0.42094706, 0.95377637]])

In [24]:
a.argsort()

array([[0, 2, 1],
       [1, 2, 0],
       [2, 1, 0],
       [1, 0, 2]], dtype=int64)

In [25]:
a.argmax()

6

In [26]:
arr2

array([[34, 23, 17],
       [78, 62, 10],
       [99, 73, 55]])

In [27]:
arr.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [28]:
b= np.arange(10)

In [29]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
type(b)

numpy.ndarray

In [31]:
b.shape

(10,)

In [32]:
arr

array([[1, 3, 5],
       [2, 6, 8],
       [3, 4, 9]])

In [33]:
arr.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [34]:
arr.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [35]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [36]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
c=np.random.rand(7,5)

In [38]:
c

array([[0.45412208, 0.68144294, 0.99168687, 0.26305422, 0.09237186],
       [0.0957905 , 0.08514832, 0.47632347, 0.76897409, 0.88869727],
       [0.79384044, 0.4110438 , 0.36777519, 0.66989895, 0.94303702],
       [0.17444355, 0.13222332, 0.08693822, 0.43858544, 0.66873684],
       [0.09194237, 0.30441637, 0.69943167, 0.58035292, 0.76796129],
       [0.41034788, 0.41936274, 0.29839644, 0.12361795, 0.36758245],
       [0.50532297, 0.69518732, 0.91443002, 0.16351704, 0.39246848]])

In [39]:
c.ravel()

array([0.45412208, 0.68144294, 0.99168687, 0.26305422, 0.09237186,
       0.0957905 , 0.08514832, 0.47632347, 0.76897409, 0.88869727,
       0.79384044, 0.4110438 , 0.36777519, 0.66989895, 0.94303702,
       0.17444355, 0.13222332, 0.08693822, 0.43858544, 0.66873684,
       0.09194237, 0.30441637, 0.69943167, 0.58035292, 0.76796129,
       0.41034788, 0.41936274, 0.29839644, 0.12361795, 0.36758245,
       0.50532297, 0.69518732, 0.91443002, 0.16351704, 0.39246848])

In [40]:
c.argsort(axis=1)

array([[4, 3, 0, 1, 2],
       [1, 0, 2, 3, 4],
       [2, 1, 3, 0, 4],
       [2, 1, 0, 3, 4],
       [0, 1, 3, 2, 4],
       [3, 2, 4, 0, 1],
       [3, 4, 0, 1, 2]], dtype=int64)

In [41]:
np.shape(c)

(7, 5)

In [42]:
c.reshape(5,7)

array([[0.45412208, 0.68144294, 0.99168687, 0.26305422, 0.09237186,
        0.0957905 , 0.08514832],
       [0.47632347, 0.76897409, 0.88869727, 0.79384044, 0.4110438 ,
        0.36777519, 0.66989895],
       [0.94303702, 0.17444355, 0.13222332, 0.08693822, 0.43858544,
        0.66873684, 0.09194237],
       [0.30441637, 0.69943167, 0.58035292, 0.76796129, 0.41034788,
        0.41936274, 0.29839644],
       [0.12361795, 0.36758245, 0.50532297, 0.69518732, 0.91443002,
        0.16351704, 0.39246848]])

In [43]:
c=c+10


In [44]:
c.T

array([[10.45412208, 10.0957905 , 10.79384044, 10.17444355, 10.09194237,
        10.41034788, 10.50532297],
       [10.68144294, 10.08514832, 10.4110438 , 10.13222332, 10.30441637,
        10.41936274, 10.69518732],
       [10.99168687, 10.47632347, 10.36777519, 10.08693822, 10.69943167,
        10.29839644, 10.91443002],
       [10.26305422, 10.76897409, 10.66989895, 10.43858544, 10.58035292,
        10.12361795, 10.16351704],
       [10.09237186, 10.88869727, 10.94303702, 10.66873684, 10.76796129,
        10.36758245, 10.39246848]])

# Other examples

In [45]:
num=np.arange(1,100,5)

In [46]:
num

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [47]:
d=np.linspace(1,100,10)

In [48]:
d

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [49]:
np.ndim(d)

1

In [50]:
np.size(d)

10

In [51]:
np.count_nonzero(arr)

9

In [52]:
arr

array([[1, 3, 5],
       [2, 6, 8],
       [3, 4, 9]])

In [61]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [60]:
arr[1,2]=0

In [62]:
arr

array([[1, 3, 5],
       [2, 6, 0],
       [3, 4, 9]])

# lets get the size difference of python array vs numpy array(in bytes)

In [63]:
import sys

In [71]:
python_array=[2,3,4,5]

In [72]:
numpy_array=np.array(python_array)

In [73]:
sys.getsizeof(1)*len(python_array)

112

In [74]:
numpy_array.itemsize*numpy_array.size

16